name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: create credentials file
      run:
        echo '${{ secrets.env_file }}' > .env
    - name: Build and run
      run: |
        docker build . --tag swe-lab
        docker run -d -p 80:80 --env-file .env swe-lab